./gradlew 'clean',
':auto-receiver:clean',
':auto-receiver:build',
':auto-receiver:publish',
':auto-receiver-annotation:clean',
':auto-receiver-annotation:build',
':auto-receiver-annotation:publish',
':auto-receiver-compiler:clean',
':auto-receiver-compiler:build',
':auto-receiver-compiler:publish'